name: Deploy to VPS

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: SSH Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Utilisez le bon nom de dépôt
            if [ -d "porjet_docker_compose" ]; then
              echo "Le répertoire porjet_docker_compose existe déjà, mise à jour du dépôt."
              cd porjet_docker_compose
              git pull https://${{ secrets.GITHUB_TOKEN }}@github.com/oussamajomaa/porjet_docker_compose.git
            else
              echo "Le répertoire porjet_docker_compose n'existe pas, clonage du dépôt."
              git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/oussamajomaa/porjet_docker_compose.git
              cd porjet_docker_compose
            fi
            docker compose down
            docker compose up -d --build --force-recreate


            
