name: Deploy to VPS

on:
  push:
    branches: [ master ]


jobs:
  deploy:
    name: SSH & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false # Important pour éviter les conflits

      - name: Déploiement via SSH sur VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          # port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            
            git clone git@github.com:osmjom/projet_docker_compose.git || true
            cd projet_docker_compose
            git pull origin main
            docker compose up -d --build