name: Deploy to VPS
on:
  push:
    branches: [master, main]

jobs:
  deploy:
    name: SSH & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Déploiement via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Configuration SSH pour GitHub
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
            # Supprime les éventuels sauts de ligne
            tr -d '\n' < ~/.ssh/id_rsa > ~/.ssh/id_rsa.tmp && mv ~/.ssh/id_rsa.tmp ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            
            # Clonage du dépôt
            if [ -d "projet_docker_compose" ]; then
              cd projet_docker_compose
              git fetch && git reset --hard origin/main
            else
              git clone git@github.com:osmjom/projet_docker_compose.git
              cd projet_docker_compose
            fi
            
            # Déploiement Docker
            docker compose down
            docker compose up -d --build --force-recreate