name: Deploy to VPS

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    name: SSH & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Déploiement via SSH sur VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/projet_docker_compose || git clone https://github.com/oussamajomaa/porjet_docker_compose.git
            cd projet_docker_compose
            git pull
            docker-compose down 
            docker-compose up -d --build