name: Deploy to VPS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: SSH & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Déploiement via SSH sur VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~
            if [ ! -d "projet_docker_compose/.git" ]; then
              git clone https://github.com/osmjom/projet_docker_compose.git projet_docker_compose
            fi

            cd projet_docker_compose
            git pull origin main
            docker-compose down
            docker-compose up -d --build
